# Generated by Django 4.2.6 on 2023-11-15 22:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{3,}$', 'Only alphanumeric characters are allowed.')])),
                ('description', models.CharField(blank=True, max_length=530)),
                ('due_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
