# Generated by Django 4.2.6 on 2023-11-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='inviting_team',
        ),
    ]
