# Generated by Django 4.2.6 on 2023-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notification_remove_task_id_team_team_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('lane_name', models.CharField(max_length=100)),
                ('lane_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
