# Generated by Django 4.2.6 on 2023-11-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_publication_team_article'),
        ('tasks', '0002_task'),
    ]

    operations = [
    ]
