# Generated by Django 4.2.6 on 2023-11-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notification_task_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lane',
        ),
    ]
