# Generated by Django 4.2.6 on 2023-11-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_invite_inviting_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='inviting_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.team'),
        ),
    ]
