# Generated by Django 4.2.6 on 2023-11-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_publication_team_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Newspaper',
        ),
    ]
