# Generated by Django 4.2.6 on 2023-11-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_notification_task_name_user_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitenotification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tasknotification',
            name='id',
        ),
        migrations.AddField(
            model_name='invitenotification',
            name='notification_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.notification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='notification_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.notification'),
            preserve_default=False,
        ),
    ]
