# Generated by Django 4.2.6 on 2023-11-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_article_newspaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
