# Generated by Django 4.2.6 on 2023-12-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lane',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.lane'),
        ),
    ]
