# Generated by Django 4.2.6 on 2023-12-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_lane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lane',
            options={'ordering': ['lane_order']},
        ),
        migrations.AddField(
            model_name='lane',
            name='lane_order',
            field=models.IntegerField(default=0),
        ),
    ]
