# Generated by Django 4.2.6 on 2023-11-18 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_newspaper_delete_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_message', models.TextField(blank=True, max_length=100)),
                ('invited_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inviting_team_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.team')),
            ],
        ),
    ]
