# Generated by Django 4.2.6 on 2023-12-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_lane'),
        ('tasks', '0004_alter_task_lane'),
    ]

    operations = [
    ]
