# Generated by Django 4.2.6 on 2023-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_invitenotification_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(choices=[('AS', 'Assignment'), ('DL', 'Deadline')], default='AS', max_length=2),
        ),
    ]
