# Generated by Django 4.2.6 on 2023-12-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_assigned_team_alter_task_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.team'),
        ),
    ]
