# Generated by Django 4.2.6 on 2023-12-07 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_lane_options_lane_lane_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lane',
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_word', message='Enter a valid word with at least 3 alphanumeric characters (no special characters allowed).', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
    ]
