# Generated by Django 4.2.6 on 2023-11-18 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='inviting_team_name',
        ),
        migrations.AddField(
            model_name='invite',
            name='invited_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='inviting_team',
            field=models.ManyToManyField(to='tasks.team'),
        ),
    ]
