# Generated by Django 4.2.6 on 2023-11-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_invite_invited_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='users',
            new_name='team_members',
        ),
    ]
