# Generated by Django 4.2.6 on 2023-12-07 21:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_notification_task_name_user_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_keydates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), null=True, size=None),
        ),
    ]
