# Generated by Django 4.2.6 on 2023-11-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_team_team_member_names_alter_team_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member_names',
        ),
    ]
