# Generated by Django 4.2.6 on 2023-12-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_deadline_keydates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline_keydates',
        ),
    ]
