# Generated by Django 4.2.6 on 2023-11-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_team_team_member_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(default='Reject', max_length=30),
        ),
    ]
