# Generated by Django 4.2.6 on 2023-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_deadline_keydates'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_notif_sent',
            field=models.BooleanField(default=False),
        ),
    ]
