# Generated by Django 4.2.6 on 2023-12-09 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_deadline_notif_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_notif_sent',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
    ]
