# Generated by Django 4.2.6 on 2023-12-10 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_deadline_notif_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='lane_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_lane_name', message='Enter a valid word with at least 1 alphanumeric character (no special characters allowed).', regex='^[a-zA-Z0-9 ]{1,}$')]),
        ),
        migrations.AlterField(
            model_name='lane',
            name='lane_order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
