# Generated by Django 4.2.6 on 2023-12-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_lane_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='team',
        ),
    ]
