# Generated by Django 4.2.6 on 2023-12-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_lane_lane_order_alter_lane_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lane',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lane',
            name='lane_order',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.RemoveField(
            model_name='lane',
            name='team',
        ),
    ]
