# Generated by Django 4.2.6 on 2023-12-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_lane_unique_together_alter_lane_lane_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='lane_order',
            field=models.IntegerField(default=0),
        ),
    ]
