# Generated by Django 4.2.6 on 2023-12-11 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_lane_team_alter_lane_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_word', message='Enter a valid word with at least 3 alphanumeric characters (no special characters allowed).', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
    ]
